image: pypi/pybuilder:latest

stages:
  - build
#   - validate
  - test
  - coverage

before_script:
    ["python -m venv venv",
     "source venv/bin/activate",
     "pip install pybuilder",
     "ls",
     "pyb clean"]

build:
  stage: build
  script:
      pyb verify
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
       - ./target

# flake8:
# 	stage: validate
# 	script:
#         pyb 

test:
  stage: test
  script:
    pyb run_unit_tests
    # pyb run_integration_tests


cov:
  stage: coverage
  dependencies:
    - test
  script:
    - pyb coverage
    - coverage=$(awk '$1 ~ "overall_coverage"' target/reports/pybuilder.plugins.python.unittest_plugin.run_unit_tests_coverage.json)
    - printf "$coverage"
  coverage: '/Code coverage: \d+\.\d+/'
