image: pypi/pybuilder:latest

stages:
  - build
#   - validate
  - test
#   - coverage

before_script:
    ["python -m venv venv",
    "source venv/bin/activate",
    "pip install pybuilder",
    "ls",
    "pyb clean"]

build:
  stage: build
  script:
      pyb verify
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
       - ./target

# flake8:
# 	stage: validate
# 	script:
#         pyb 


test:
  stage: test
  script:
    pyb run_unit_tests
    # pyb run_integration_tests


#coverage:
#	stage: coverage
#	script:
#		- coverage=$(awk -F"," '{ branches += $6 + $7; covered += $7 } END { print "Total" ,int(100*covered/branches), "%% covered" } file.fileType)
#		coverage: '\d+(\.\d+)?'
